use std::fmt;
use std::str::FromStr;

#[derive(Debug, Copy, Clone, PartialEq)]
pub enum FilterCategory {
    SourceFile,
    BlockedUri,
    ScriptSample,
    Referrer,
    DocumentUri,
    OriginalPolicy,
}

impl FromStr for FilterCategory {
    type Err = &'static str;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "source_file" => Ok(FilterCategory::SourceFile),
            "blocked_uri" => Ok(FilterCategory::BlockedUri),
            "script_sample" => Ok(FilterCategory::ScriptSample),
            "referrer" => Ok(FilterCategory::Referrer),
            "document_uri" => Ok(FilterCategory::DocumentUri),
            "original_policty" => Ok(FilterCategory::OriginalPolicy),
            _ => Err("Unknown FilterCategory (available values: source_file, blocked_uri, script_sample, referrer, document_uri, original_policty)"),
        }
    }
}

impl fmt::Display for FilterCategory {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{:?}", self)
    }
}

pub const SOURCE_FILE_FILTERS: &[&str] = &[
    "chromenull://",
    "resource://",
    "chrome-extension://",
    "safari-extension://",
    "se-extension://",
    "chrome://kango-",
    "netdefender/hui/ndhui.js",
    "twitbridge.com/ads",
    "tags.clickintext.net",
    "davebestdeals.com",
    "ZennoPoster",
    "jar:file",
    "akamaihd.net",
    "ze406soi.ru",
    "mxaddon-pkg",
    "rsc.cdn77.org",
    "data1.",
    "bindo.js",
    "wd7bdb20e4d622f6569f3e8503138c859d.win",
    "simple-finder.com",
    "s3.amazonaws.com/js-cache",
    "static.hotjar.com",
];

pub const BLOCKED_URI_FILTERS: &[&str] = &[
    "mxjscall://",
    "res://",
    "safari-resource://",
    "chromenull://",
    "chromeinvoke://",
    "chromeinvokeimmediate://",
    "crwebnull://",
    "crwebinvoke://",
    "crwebimmediate://",
    "mbinit://",
    "opera://",
    "none://",
    "chrome-extension:/",
    "safari-extension:/",
    "webviewprogressproxy://",
    "gsa://onpageload",
    "mx://",
    "https://www.gstatic.com/images/branding/product/2x/translate_24dp.png",
    "android-webview",
    "adblockers.opera-mini.net",
    "ms-browser-extension",
    "http://91.68.209.",
    "getpingu.com/assets",
    "reek.github.io/anti-adblock-killer",
    "savingsslider-a.akamaihd.net",
    "app.abtasty.com",
    "dataloading.net",
    "fireads.men",
    "rdc.apicit.net",
    "comic-sans-replacer",
    ".davebestdeals.com",
    "loadingdata.site",
    "ashishmishra.in/gridify",
    "jsl.infostatsvc.com",
    "assets.volcanicpixels.com",
    "loadingpages.me",
    "loadingpages.info",
    "loadingpage.info",
    "lingualeo.com",
    "cr-input.mxpnl.net",
    "adsstrike.pro",
    "null",
    "rsc.cdn77.org",
    "/data1.",
    "connectionstrenth.com",
    "secure.optibuymac.com",
    "www.stackoverflow.com",
    "cloudfront.net",
    "findizer.fr",
    "cdn.viglink.com",
    "dl.metabar.ru",
    "sxt.cdn.skype.com",
    "1.1.1.1/bmi",
    "www.googletagmanager.com",
    "wd7bdb20e4d622f6569f3e8503138c859d.win",
    "partner-net.men",
    "undroider.com",
    "i2.cdscdn.com/imagesok/mco/btUp.png",
    "adnotbad.com",
    "QualityCheck/ga.js",
    "ssl.gstatic.com/dictionary",
    "loadingpaqes.info",
    "app.trackduck.com",
    "alecyueee.us",
    "pllaff-up.ru",
    "192.168.1",
    "cursorsfolder/mickey-hand.png",
    "mstat.acestream.net",
    "takethatad.com",
    "cdnsure.com",
    "ssl.google-analytics.com",
    "mc.yandex.ru",
    "myshopmatemac.com",
    "spidtest.org",
    "www.paperkarma.com/images/app_store.png",
    "cdnnetwok.xyz",
    "istatic.eshopcomp.com",
    "substantielwww.dyndns.org",
    "extenjo.net",
    "fdz.octapi.net",
    "inter.gamefunnetwork.com",
    "loadingpagesos.download",
    "spedcheck.space",
    "ffoodd/a11y.css",
    "canvaspl-a.akamaihd.net",
    "savingsslider-a.akamaihd.net",
    "www.ciuvo.com",
    "loadingpabes.info",
    "loadingpageson.science",
    "loadingpagesos.bid",
    "loadingpagesose.date",
    "loadingpagesson.club",
    "loadingpales.info",
    "nonfas.us",
    "querfi.us",
    "gamephrase.com",
    "elsewheregames.com",
    "getpocket.com",
    "moz-extension",
    "lnkr.us",
    "urlvalidation.com",
    "adrs.me",
    "adserv.info",
    "amiok.org",
    "analyzecdn.xyz",
    "analyzenetwork.xyz",
    "bootstrapnet.space",
    "butstrap.space",
    "cdnanalytics.xyz",
    "cdncash.com",
    "cdncash.net",
    "cdncash.org",
    "cdnclntr.com",
    "cdnjs.space",
    "cdnlvry.xyz",
    "cdnnetwok.xyz",
    "cdnstr.xyz",
    "cdnswf.xyz",
    "cdnvalid.xyz",
    "connectionstrenth.com",
    "domainanalyzing.xyz",
    "domaincdn.xyz",
    "domainvalidation.xyz",
    "eluxer.net",
    "flowanalytic.site",
    "ge0ip.com",
    "ge0ip.net",
    "ge0ip.org",
    "glganltcs.space",
    "glgnltks.xyz",
    "icontent.us",
    "infoanalytics.tools",
    "infoprovider.group",
    "intrnlcss.xyz",
    "jsfuel.com",
    "lancheck.net",
    "metrext.com",
    "netanalitics.space",
    "netanalytics.xyz",
    "netanalyzer.space",
    "netcheckcdn.xyz",
    "netstats.space",
    "netwcdn.xyz",
    "networkanalytics.xyz",
    "networkcheck.xyz",
    "ratexchange.net",
    "serverads.net",
    "siteheart.net",
    "spaceshipad.com",
    "spidtest.space",
    "statcounter.biz",
    "statvalidation.website",
    "thisadsfor.us",
    "tradeadsexchange.com",
    "trafficvalidation.tools",
    "trendtext.eu",
    "validanalytics.xyz",
    "validationcdn.xyz",
    "validcdn.xyz",
    "validcndnet.xyz",
    "validdomain.xyz",
    "whatzmyip.net",
    "worldnaturenet.xyz",
    "www1.thrgh.space",
    "www4.thrgh.space",
    "www5.thrgh.space",
    "www7.thrgh.space",
    "www8.thrgh.space",
    "www9.thrgh.space",
    "ydpi.pw",
    "getstencil.com",
    "elsewheregames.com",
    "fungamesshop.com",
    "gameandslash.com",
    "gamephrase.com",
    "gamersurface.com",
    "pinballpal.com",
    "mozbar.moz.com",
    "gj.track.uc.cn",
];

pub const SCRIPT_SAMPLE_FILTERS: &[&str] = &[
    ";(function installGlobalHook(window)",
    "var FuckAdBlock = function",
    "var BlockAdBlock = function",
    "@media print {#UNIQUE_ID-ghostery",
    "@media print {#ghostery-purple-box",
    "@media print {#ghostery-button",
    "{safeWindow:{",
    "onsubmit attribute on DIV element",
    "onchange attribute on DIV element",
    "onfocusin attribute on DIV element",
    "onselectstart attribute on DIV element",
    "embed[height=",
    "window.AG_onLoad = function",
    "AG_onLoad=function(func)",
    "root .mod > ._jH + .rscontainer",
    "window.oldSetTimeout=window.setTimeout",
    "window.devToolsOptions = Object.",
    "dummyRuleForDigg{}",
    "Copyright 2014 Evernote",
    "http://www.faceporn.net/",
    "Cacaoweb = { callbackIsRunning",
    "if (window.google && (window.google.sn",
    "__webpack_require",
    "e={Vue:null",
    "_PostRPC()",
    ".password-toggler-button-parent",
    "allowAdblock()",
    ".topbanneradvertise",
    ".wrcx {display:none}",
    "rw_sendSocketMessage(aData)",
    "window[\"_gaUserPrefs\"]",
    "function n(){!function(){function",
    "ng:cloak",
    "window._ngInspect_clickedEl",
    ".werbung, .text_werbung",
    "webPageNotificationsController",
    "var delay = null; currDisplay = null",
    "var AttachStyleEnum",
    "ISAnalysterLoader",
    "ISCommonAnalyster",
    "This is not a zero-length file",
    "var api = {};",
    "cloudflare-app[app-id=",
    ".adbmodal-cloudflare-open",
    "function injectPageScriptAPI",
    "#Ad2, #AdText, #Ad_Top",
    "#A9AdsMiddleBoxTop",
    "background-image: url(resource://jid1",
    "#forecastfox",
    ".minvid__overlay__container",
    ".password-toggler-button-parent",
    "#toggleGifsOverlay",
    "function s(t,n,e,r){t",
    "onclick=\"fileice()\"",
    ".pubblicita, .adv_esterno",
    "img[src=\"https://www.paypalobjects.com",
    "function installHook (window)",
    "body#dummybodyid .diigolet",
    "document.addEventListener(\'mousedown\'",
    ".trc_related_container div[data-item",
    "@media screen {@font-face{font-family:\'O",
    "function injected(eventName, injectedIn",
    "const V8_STACK_",
    ":root audio[data-",
    "moz-extension://",
    "a[rel~=\'nofollow\']{outline",
    "document.currentScript.setAttribute",
    "Many CSS class names in this file",
    ".vimvixen-console-frame",
    ".cip-genpw-icon.cip-icon-key-small",
    "function detect (win)",
    "iframe {display: none;}",
    "try{(function overrideDefaultMethods",
    "@-webkit-keyframes load4",
    "contextMenu.js",
    ".seo-highlighter",
    "function(vimiumOnClickAttributeName)",
    "Highlight style classes",
    "window.klTabId_kis",
    "navigator.__defineGetter__",
    ".reclame, .advertenties, .advertentie",
    "function (NAVIGATOR, OBJECT)",
    "function(e){let t={};if(e.hasOwnProper",
    "window.loop11ExtTerritory = true",
    "s3gt_translate_tooltip_mini",
    ";undefined",
    ".ggbox",
    "admixer_",
    ".twkv.ru",
    "window.script15",
    ".tota11y-dark-color-scheme",
    "onclick attribute on MENUITEM element",
    "Date.prefs =",
];

pub const REFERRER_FILTERS: &[&str] = &[
    "http://l.facebook.com",
    "https://l.facebook.com",
    "feedly.com",
    "int.search.myway.com",
    "web.skype.com",
    "material.io",
    "www.netvibes.com",
    "l.messenger.com",
    "mamot.fr",
    "plus.url.google.com",
    "m.facebook.com",
    "&source=hangouts",
];

pub const ORIGINAL_POLICY_FILTERS: &[&str] = &[".blackspider.com"];
